### ISSUE TITLE
snap does not work

### ISSUE THREAD

**Issue by sp-apertus** [apertus-open-source-cinema/axiom-firmware#119]
the current version in the latest release (nightly #33 b9cbb06) of snap does not seems to work.

When it is executed it seems to idle until cancelled.

The original old binary for reference (which does works when downloaded to the Beta):

http://vserver.13thfloor.at/Stuff/AXIOM/cmv_snap3
http://vserver.13thfloor.at/Stuff/AXIOM/cmv_snap3.static

**Comment by anuejn** [comment]
is this fixed?

**Comment by sp-apertus** [comment]
Have no beta to confirm I am afraid.

**Comment by anuejn** [comment]
ok

**Comment by sp-apertus** [comment]
tested, fixed
