### ISSUE TITLE
add current bitstreams to git

### ISSUE THREAD

**Issue by rroohhh** [apertus-open-source-cinema/axiom-firmware#128]
At the moment bitstreams are downloaded from http://vserver.13thfloor.at/Stuff/AXIOM/ during the firmware build. This means they could change without anybody noticing, making tracking down bugs pertaining to them more difficult.

While we figure out how to build the bitstreams in the CI (#71) we should atleast move the prebuilt bitstreams into a git repository and include them from there.

**Comment by anuejn** [comment]
fixed in https://github.com/apertus-open-source-cinema/axiom-firmware/commit/33e9417a32645305d74e344f9fa7b9d11d47ccc8
