### ISSUE TITLE
Bertls wishlist

### ISSUE THREAD

**Issue by sp-apertus** [apertus-open-source-cinema/axiom-firmware#157]
- have vi actually be vim
- use set mouse=r (so that mouse copy works)
 - get an alias for ls -la (i.e. ll)
- remove the -nH from the 'grep' alias as it messed with piped (stdin) grep
- devmem -> memtools

**Comment by rroohhh** [comment]
Done in fb4149086a4d8815bc7eb4d44a96a50c24b735c0 and f39e79326df22cde55b6d45c2841466617ec77c2
