### ISSUE TITLE
Avoid ANSI/VT100 color codes which generate a 'blink' effect in minicom

### ISSUE THREAD

**Issue by herbertp** [apertus-open-source-cinema/axiom-firmware#163]
Certain ANSI/VT100 color codes get interpreted by minicom (both color and mono mode) as 'blink' attribute which leads to a very annoying blinking text on the serial console.

Currently this is the case for the user and host name in the PS1 prompt after login.

```
[operator@beta] ~ $ 
[        @    ]     
[operator@beta] ~ $ 
[        @    ]     
```

**Comment by rroohhh** [comment]
Fixed in 51baf2a, for some reason I didn't commit the changes to the prompt...
