### ISSUE TITLE
vi/vim mouse mode breaks normal copy/paste behaviour

### ISSUE THREAD

**Issue by herbertp** [apertus-open-source-cinema/axiom-firmware#166]
The default mouse mode set for vim has changed and now any right-click and drag selection becomes a 'vim' selection instead of going to the clipboard.

This can be easily fixed with setting it to 'r' (or 'v') instead of 'a'.

`mouse=r`

**Comment by rroohhh** [comment]
fixed in 47495349db863ed11b611674d02d03028ddf8c47
