### ISSUE TITLE
Wifi Speed Improvements?

### ISSUE THREAD

**Issue by sp-apertus** [apertus-open-source-cinema/axiom-firmware#180]
I am using the Edimax 150 Nano Wifi stick and it works out of the box on the Beta. 

But speed could be better though, I achieve transfer speeds of raw12 images over SSH (surely not the most optimal method performance wise) of around 140kb/s max to a laptop 1m away from the camera which means a raw12 frame takes around 2 minutes to download.

Do you see any potential configuration improvements on the Beta to increase the Wifi performance?

**Comment by rroohhh** [comment]
While there seem to be alternative drivers they don't support station mode so we can't really use them.

Closing for now as we have found other wifi sticks that work better.
